config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  root to: "pages#index"
  get "/search" => "search#index"
  devise_for :users

  resources :books, only: [:index, :show]
  resources :listings, only: [:index, :new, :create]
  resources :users, only: [:show]
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :isbn
  validates_uniqueness_of :isbn

  belongs_to :section
  has_many :listings

  def self.by_title(title)
    where('LOWER(title) LIKE LOWER(?)', "%#{title}%")
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :sections
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates_presence_of :user
  validates_presence_of :book
  validates_presence_of :price
  validates_numericality_of :price, greater_than_or_equal_to: 0

  def self.by_title(title)
    joins(:book).where('LOWER(title) LIKE LOWER(?)', "%#{title}%")
  end

  def self.active
    where(active: true)
  end

  def self.inactive
    where(active: false)
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :books
end

app/models/term.rb
class Term < ActiveRecord::Base
  has_many :departments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.where(nil)
    @books = @books.by_title(params[:q]) if params[:q].present?
  end

  def show
    @book = Book.find(params[:id])
    @listings = @book.listings.active
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @listings = Listing.by_title(params[:q]).active
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @listing.active = true

    if @listing.save
      redirect_to listings_path
    else
      render "new"
    end
  end

  private

  def listing_params
    params[:listing].permit(:book_id, :user_id, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @books = Book.by_title(params[:q]).limit(10)
    @listings = Listing.by_title(params[:q]).active.limit(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @listings = @user.listings.active
  end
end

app/views/books/index.html.erb
<div class="row">

<div class="col-sm-12">
  <h3>Showing results for '<%= params[:q] %>'</h3>
  <hr>
</div>

<div class="col-sm-9">
  <h4>Books</h4>
  <%= render "shared/books_grid" %>
</div>

<div class="col-sm-3">
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to "All", search_path(utf8: params[:utf8], q: params[:q]) %></li>
    <li><%= link_to "Listings", listings_path(utf8: params[:utf8], q: params[:q]) %></li>
    <li><%= link_to "Books", books_path(utf8: params[:utf8], q: params[:q]) %></li>
  </ul>
</div>

</div>

app/views/books/show.html.erb
<div class="row">
  <div class='col-sm-3'>
    <img class="img-responsive hidden-xs" src="<%= @book.image %>">
    <h4><%= @book.title %></h4>
    <p><%= @book.author %></p>
    <p><%= @book.isbn %></p>
  </div>

  <div class='col-sm-9'>
    <h4>Listings</h4>
    <%= render "shared/listings" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Paperbacks" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class: "navbar-brand" do %>
              <%= image_tag "icon.svg", alt: "Paperbacks" %>
            <% end %>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <div class="nav navbar-nav navbar-form">
              <%= form_tag search_path, role: "search", method: "get" do %>
                <div class="form-group">
                  <input id="global-search" type="text" name="q" class="form-control"
                         placeholder="Search Paperbacks" value="<%= params[:q] %>">
                </div>
              <% end %>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <% if current_user.admin? %>
                  <li><%= link_to "Dashboard", rails_admin.dashboard_path %></li>
                <% end %>
                <li><%= link_to "New Listing", new_listing_path %></li>
                <!-- <li><%= link_to "My Account", nil %></li> -->
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>

    <!--
      <footer id="footer">
      <a href="http://twitter.com/getpaperbacks">Twitter</a>
      <a href="https://github.com/jonahgeorge/paperbacks">GitHub</a>
      </footer>
    -->
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/listings/index.html.erb
<div class="row">

<div class="col-sm-12">
  <h3>Showing results for '<%= params[:q] %>'</h3>
  <hr>
</div>

<div class="col-sm-9">
  <h4>Listings</h4>
  <%= render "shared/listings" %>
</div>

<div class="col-sm-3">
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to "All", search_path(utf8: params[:utf8], q: params[:q]) %></li>
    <li><%= link_to "Listings", listings_path(utf8: params[:utf8], q: params[:q]) %></li>
    <li><%= link_to "Books", books_path(utf8: params[:utf8], q: params[:q]) %></li>
  </ul>
</div>

</div>

app/views/listings/new.html.erb
<div class='col-sm-6 col-sm-offset-3'>

<% if @listing.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>New Listing</h3>

<%= form_for @listing do |f| %>
  <div class="form-group">
    <%= f.label :book, class: "control-label" %>
    <%= f.select :book_id, options_from_collection_for_select(Book.all, :id, :title, {:selected => @listing.book_id}), {:include_blank => true}, class: "form-control" %>
  </div>
</div>

<div class='col-sm-6 col-sm-offset-3'>
  <div class="form-group">
    <%= f.label :price, class: "control-label" %>
    <div class="input-group">
      <span class="input-group-addon">$</span>
      <%= f.number_field :price, min: 0, step: 0.25, class: "form-control" %>
    </div>
    <p class="help-block">Let's keep things realistic here- we're all students after all.</p>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-success rmarg10" %>
    <%= link_to "Cancel", root_path %>
  </div>
<% end %>
</div>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>&lt;Generic Landing Page/&gt;</h1>
</div>

app/views/root/index.html.erb
<div class="intro">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
          <h1>Shit happens — <br> Be on top of it.</h1>
          <p class="subtext">Sentry gives you insight into the errors that affect your customers.</p>
          <p><a href="#" class="cta pricing-link">Get Started</a></p>
      </div>
      <div class="col-sm-8">
        <ul class="screenshots hidden-xs">
          <!-- <li><img src="https://www.getsentry.com/_static/getsentry/images/screenshots/event-detail.png" alt="Sentry Dashboard"></li> -->
          <!-- <li><img src="https://www.getsentry.com/_static/getsentry/images/screenshots/teams.png" alt="Sentry Dashboard"></li> -->
          <!-- <li><img src="https://www.getsentry.com/_static/getsentry/images/screenshots/stream.png" alt="Sentry Dashboard"></li> -->
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="the-old-way">
  <div class="container">
    <h2>Stop logging exceptions the old fashioned way.</h2>

      <p><strong>Chances are that you have errors in your log files you are not aware of.</strong> Sentry surfaces these errors, helps you gauge severity and frequency, and then gives you the information necessary to fix them quickly.</p>

  </div>
</div>

<div class="benefits">
    <div class="container">
        <h3 class="centered"><span>In just a few minutes from now you’ll be able to:</span></h3>
        <div class="row">
            <div class="col-sm-4">
                <div class="circle">
                    <span class="badge">3</span>
                    <span class="icon icon-repeat"></span>
                </div>
                <h4>See the impact of deploys in real-time</h4>
                <p>Watch Sentry as you deploy to make sure new changes don’t have an unexpected impact on your users</p>
            </div>
            <div class="col-sm-4">
                <div class="circle">
                    <span class="icon icon-heart"></span>
                </div>
                <h4>Provide next-level support to your users.</h4>
                <p>Users interrupted by an error tend to move on. Use the information that Sentry logs to bring them back.</p>
            </div>
            <div class="col-sm-4">
                <div class="circle">
                    <span class="icon icon-cross"></span>
                </div>
                <h4>Detect and thwart<br> fraud as its attempted.</h4>
                <p>Get notified of unusual amounts of failures on purchases, authentication, and other sensitive areas of your app.</p>
            </div>
        </div>
    </div>
</div>

<div class="customers">
    <div class="container">
        <h2>And you'll be in good company.</h2>
        <div class="row quotes">
            <div class="col-sm-4">
                <div class="photo">
                    <img src="https://www.getsentry.com/_static/getsentry/images/testimonials/kristjan.jpg">
                </div>
                <blockquote><p>"Using Sentry has been a simple and intuitive experience and support has been virtually instant for any questions that have come up."</p></blockquote>
                <p>
                    <cite>Kristján Valur Jónsson</cite>
                    <img class="company" src="https://www.getsentry.com/_static/getsentry/images/usedby/ccp.svg" width="60px" style="position:relative; top: -10px;">
                </p>
            </div>
            <div class="col-sm-4">
                <div class="photo">
                    <img src="https://www.getsentry.com/_static/getsentry/images/testimonials/philip.jpg">
                </div>
                <blockquote><p>"Sentry provides us with a real time view of system health and, almost more importantly, the impacts of new deploys as <br>they happen."</p></blockquote>
                <p>
                    <cite>Philip Forget</cite>
                    <img class="company" src="https://www.getsentry.com/_static/getsentry/images/usedby/readability.svg" width="120px">
                </p>
            </div>
            <div class="col-sm-4">
                <div class="photo">
                    <img src="https://www.getsentry.com/_static/getsentry/images/testimonials/mike.jpg">
                </div>
                <blockquote><p>"Sentry helps us prioritize the most important issues impacting user experience."</p></blockquote>
                <p>
                    <cite>Mike Clarke</cite>
                    <img class="company" src="https://www.getsentry.com/_static/getsentry/images/usedby/standardtreasury.svg" width="110px" style="position: relative; top: -5px;">
                </p>
            </div>
        </div>
    </div>
</div>

app/views/search/index.html.erb
<div class="row">

<div class="col-sm-12">
  <h3>Showing results for '<%= params[:q] %>'</h3>
  <hr>
</div>

<div class="col-sm-9">
  <h4>Books</h4>
  <%= render "shared/books_row" %>
  <br>

  <h4>Listings</h4>
  <%= render "shared/listings" %>
</div>

<div class="col-sm-3">
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to "All", search_path(utf8: params[:utf8], q: params[:q]) %></li>
    <li><%= link_to "Listings", listings_path(utf8: params[:utf8], q: params[:q]) %></li>
    <li><%= link_to "Books", books_path(utf8: params[:utf8], q: params[:q]) %></li>
  </ul>
</div>

</div>

app/views/shared/_books_grid.html.erb
<div class='flex-grid'>
  <% @books.each do |book| %>
    <%= link_to book, class: 'flex-grid-item' do %>
      <img class='artwork' src='<%= book.image %>' height=150 width=100>
      <p class='title'><%= book.title %></p>
    <% end %>
  <% end %>
</div>

app/views/shared/_books_row.html.erb
<div class='flex-row'>
  <% @books.each do |book| %>
    <%= link_to book, class: 'flex-row-item' do %>
      <img class='artwork' src='<%= book.image %>' height=150 width=100>
      <p class='title'><%= book.title %></p>
    <% end %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, class: "alert alert-#{key}", role: "alert" do %>
    <%= value.html_safe %>
    <button class='close' type="button" data-dismiss="alert">
      <span aria-hidden="true">×</span>
      <span class='sr-only'>Close</span>
    </button>
  <% end %>
<% end %>

app/views/shared/_listings.html.erb
<table class='table'>
  <thead>
    <th>Book</th>
    <% unless defined? hide_seller and hide_seller %>
      <th>Seller</th>
    <% end %>
    <th>Last Updated</th>
    <th>Price</th>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= link_to listing.book.title, listing.book %></td>
        <% unless defined? hide_seller and hide_seller %>
          <td><%= link_to listing.user.name, listing.user %></td>
        <% end %>
        <td><%= time_ago_in_words listing.updated_at %> ago</td>
        <td>
          <%= mail_to listing.user.email, :class => 'btn btn-default btn-xs', :type => 'button' do %>
            <%= number_to_currency(listing.price) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class='col-sm-12'>
  <h4><%= @user.name.possessive %> Listings</h4>
  <%= render partial: "shared/listings", :locals => { :hide_seller => true } %>
</div>